name: Build Project

on:
  workflow_dispatch:

concurrency:
  group: "build-and-upload"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup `node`
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - name: Restore `lively.next` installation
        id: cache-lively
        uses: actions/cache/restore@v3
        env:
          cache-name: lively-repo
          ref: 089c8731c6c9187f85257add517234acf9fd7a4c
        with:
          path: .            
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.ref }}
      - name: Checkout `lively.next`
        if: ${{ steps.cache-lively.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v3
        with:
          repository: LivelyKernel/lively.next
          ref: 089c8731c6c9187f85257add517234acf9fd7a4c
      - name: Install `lively.next`
        if: ${{ steps.cache-lively.outputs.cache-hit != 'true' }}
        run: |
          chmod a+x ./install.sh
          ./install.sh --freezer-only
      - name: Save `lively` installation in cache
        if: ${{ steps.cache-lively.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v3
        env:
          cache-name: lively-repo
          ref: 089c8731c6c9187f85257add517234acf9fd7a4c
        with:
          path: .            
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.ref }}     
      - name: Checkout Project Repository
        uses: actions/checkout@v3
        with:
          path: local_projects/engageLively--ibn-battuta-new
      - name: Build Project
        run: npm run build-minified --prefix local_projects/engageLively--ibn-battuta-new
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: local_projects/engageLively--ibn-battuta-new/build